### ISSUE TITLE
Better list formatting & adding missing information

### ISSUE THREAD

**Issue by fharper** [fharper/coffeechat#26]
I created this project quickly and I don't like how the list is generated: it should be sexier!

I also added new information about the awesome people doing coffee chat, and they aren't listed yet.

**Comment by clsource** [comment]
We improved a little bit the list here https://github.com/devschile/cafecito 👍

**Comment by clsource** [comment]
It was made for a local community of devs in Chile, so it has many inside jokes. The people feel more at home with something that tailors to them.

Feel free to use the code if is useful, currently it has the following improvements:

- Table rendering instead of a list.
- Emojis
- Custom images (emoticons)
- Github, Gitlab, Codeberg links.
