### ISSUE TITLE
Dead calendly link and not really the CEO of GitHub

### ISSUE THREAD

**Issue by janwirth** [fharper/coffeechat#50]
<img width="850" alt="image" src="https://github.com/fharper/coffeechat/assets/7485959/cbe707ac-98ed-40a1-a59f-853caaf7707b">

**Comment by fharper** [comment]
Thanks, I fixed the title + company. As for the calendly, I'll ask him about that, caused it's what he added.

**Comment by fharper** [comment]
@Chukslord1 you Calendly link is 404. I updated the company + title to the CEO one as this repository cannot handle two jobs. Feel free to do another PR if you want to change the one displayed.

**Comment by Chukslord1** [comment]
> @Chukslord1 you Calendly link is 404. I updated the company + title to the CEO one as this repository cannot handle two jobs. Feel free to do another PR if you want to change the one displayed.

Hi! So i'm a Senior Technical writer at GitHub and I run my startup as the CEO at RequestMechanic.

Here's my updated calendly link https://calendly.com/chukslord1/quickmeet.

**Comment by fharper** [comment]
@Chukslord1: Oh OK, I removed it since I didn't see the GitHub job on your LinkedIn profile so I assumed it was a mistake. Also, as mentioned, this repository only support one job. If you prefer, you can do a PR to change the "CEO at RequestMechanic" for "Senior Technical writer at GitHub".

As for the Calendly link, I'll fix it for you.

I now consider this issue closed. Thanks again for reporting this @janwirth :)
